### ISSUE TITLE
`useNitroApp` was reexported when building for Cloudflare Pages

### ISSUE THREAD

**Issue by robbietjuh** [nuxt-modules/og-image#164]
Really excited to try out this project! Have it running perfectly fine locally, but when I build with `NITRO_PRESET=cloudflare-pages`, the client build succeeds, but the server build is reporting the following error:

```
Export "useNitroApp" of module "node_modules/nitropack/dist/runtime/app.mjs" was reexported through module "node_modules/nitropack/dist/runtime/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/nuxt-og-image/dist/runtime/nitro/og-image/context.mjs" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
```

The build seems to complete, but I cannot push it to Cloudflare Pages. When I do, `wrangler` reports that the build was successfully uploaded, but the Cloudflare dashboard shows that the 'deployment failed'. I cannot find any details on this.

I have prepared an example of a failing project here: https://www.github.com/robbietjuh/nuxt-og-image-playground

You can simply clone and run `NITRO_PRESET=cloudflare-pages npx nuxi build` to reproduce the error as stated above. The example project was created using `npx nuxi@latest init nuxt-og-image-playground` and pulled in `nuxt@3.10.2`, `vue@3.4.19` and `vue-router@4.2.5`. I added nuxt-og-image through `yarn add nuxt-og-image@3.0.0-rc.37`. I have also tried `rc.38` but that didn't work either (same error -- I tried using rc.37 as it seems the playground (https://nuxt-og-image-playground.pages.dev/) is also running this version and seems to be running fine).

Please let me know if you need any other information.

**Comment by awacode21** [comment]
i am having the same issue with vercel.

Export "useNitroApp" of module "node_modules/nitropack/dist/runtime/app.mjs" was reexported through module "node_modules/nitropack/dist/runtime/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
--
11:53:10.422 | Either change the import in "node_modules/nuxt-og-image/dist/runtime/nitro/og-image/context.mjs" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.

**Comment by harlan-zw** [comment]
This is an upstream issue and can be safely ignored until it's fixed

**Comment by Damian-Orzel** [comment]
So there is no way to build the project until the problem is fixed?

**Comment by harlan-zw** [comment]
This shouldn't effect the build, if the build is failing, it's a separate issue to this being logged.

**Comment by harlan-zw** [comment]
This should be fixed in RC 46

**Comment by Mgoeloe** [comment]
It's still not fixed...

**Comment by harlan-zw** [comment]
Please ignore, it will be fixed in the next Nitro major which should be landing soon. If I fix it now it will break for the major.

**Comment by Mgoeloe** [comment]
I appreciate your work, but this issue is still present in v3.0.2

**Comment by harlan-zw** [comment]
Yes please wait for the next Nitro major.

**Comment by cagataycali** [comment]
## 🔄 Cycle Update — 2026-05-06T11:25Z

### Integration Tests: ✅ BOTH PASS

| Runner | Unit Tests | Integration | Status |
|--------|-----------|-------------|--------|
| Thor (sm_110, 132GB) | 716 passed | 13p/2f/10e | ✅ |
| EC2 (L40S, 46GB) | 715 passed | 13p/2f/10e | ✅ |

### PR #85 MuJoCo Backend:
| Runner | Unit Tests | New Tests | Status |
|--------|-----------|-----------|--------|
| Thor | **1242** passed, 1 failed | +527 | ✅ |
| EC2 | **1242** passed, 1 failed | +527 | ✅ |

### Actions Taken:
1. **Fixed PR #85 CI** — `ruff format` failure on `rendering.py` (commit `29d4d3e`). CI now GREEN ✅
2. **Dispatched Thor + EC2** integration tests — both pass
3. **Report posted** — shipitfast/strands-labs#232

### Current Blockers:
- PR #85: CI ✅ GREEN, all threads resolved, needs re-approval from @yinsong1986 or @awsarron
- Single unit test failure on both runners: `torchvision.io.VideoReader` removed in PyTorch nightly (not our code)

### Run Links:
- Thor: https://github.com/cagataycali/strands-gtc-nvidia/actions/runs/25431496139
- EC2: https://github.com/cagataycali/strands-gtc-nvidia/actions/runs/25431496152
